name: Testing QuickPizza
on:
  #   - push
  - workflow_dispatch

jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      quickpizza:
        image: ghcr.io/grafana/quickpizza-local:0.2.0
        ports:
          - 3333:3333

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: script.js
        env:
          BASE_URL: "http://quickpizza:3333"
          K6_WEB_DASHBOARD: true
          K6_WEB_DASHBOARD_EXPORT: html-report.html
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: path/to/artifact/ # or path/to/artifact
